apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-webapp-deployment
  labels:
    app: profile-webapp
spec:
  replicas: 3  # Number of pods you want to run
  selector:
    matchLabels:
      app: profile-webapp
  template:
    metadata:
      labels:
        app: profile-webapp
    spec:
      containers:
        - name: profile-webapp
          image: rajeshnethunuritesting:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: azure-db-secret
                  key: spring.datasource.url
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: azure-db-secret
                  key: spring.datasource.username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azure-db-secret
                  key: spring.datasource.password
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-webapp-service
spec:
  selector:
    app: profile-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
